### PR TITLE
Add an option to diff against a specific revision, defaults to '.'

### PR DESCRIPTION
**Pull request by Goodwine**
Add an option to diff against a specific revision, defaults to `.`
    
The purpose of this change is to be able to diff against a different ancestor, like `.^` the reason for this is that if I'm still working on the same revision and I plan to run `hg amend`, then I prefer to watch diffs against `.^` or another tag instead.
    
Fixes victor-torres/atom-hg#39

### CODE REVIEW

**Comment by victor-torres** [comment]
You’re doing a nice work here, @Goodwine. Could you add some test cases, please?

**Comment by Goodwine** [comment]
Will do.
I also noticed a small bug with my PR about tags, I already have a fix and tests for that but I'll send it after I add tests to this PR

**Comment by victor-torres** [comment]
Fine

**Comment by Goodwine** [comment]
Woo, I don't know why tests failed on windows using `.^`, maybe windows needs a different format for the "previous" revision?
Anyways I think tests are ready now :smiley:

**Pull request merged**
