### PR TITLE
Async support for Atom 1.7

### PR DESCRIPTION
**Pull request by victor-torres**
As mentioned in #9 and #3. Here it comes Atom asynchronous support. 

As far as I have tested it, it's working well. The only thing I noticed is that tree-view file diff/status won't work in repositories stored at /tmp haha, but it's not really a problem 😝

This will be released with version 2.0 (yes, we're jumping from version 1.0 because, hey, async support rocks 😎).

### CODE REVIEW

**Comment by mrstebo** [comment]
Only think I noticed that was missing was that you are not destroying `@async` in the HgRepository class.
Also, from the `GitRepository` code in the atom repo, it seems like you have to call the async classes `refreshStatus` inside the the synchronous class? Not sure if that is required or not? I'll have a deeper look in to it tomorrow.

**Comment by victor-torres** [comment]
Hey. You said something I wasn't paying attention to. I'll make some tests tonight.

**Comment by victor-torres** [comment]
@mrstebo I don't know if we have to call `@async` methods from `repositoryForDirectorySync`.

If I open Atom's console and click between the code editor and the console window I can see a lag with Mercurial repositories that I can't see with git repositories. 

Seems like tree-view is using the sync version of the repository provider, but if git-repository can do it without lag why can't we do it with atom-hg?

Unfortunately I may not have the required time to further investigate this. I hope you can take a clue on it tomorrow. Keep us up to date :+1:

**Comment by mrstebo** [comment]
They are using that node-git package for wrapping calls to git...Maybe there is something in that?

Just curious, what OS are you using? I'm doing the tests on Windows 10 64bit

**Comment by victor-torres** [comment]
OS X El Capitan

**Pull request merged**
