### PR TITLE
Show branch:bookmark instead of just branch.

### PR DESCRIPTION
**Pull request by danielmachado**

### CODE REVIEW

**Comment by victor-torres** [comment]
Nice work, @danielmachado.

Could you add some test cases, please?!

Thanks.

**Comment by TomKemperNL** [comment]
I've manually tested it, and won't mind adding some automated tests later this (maaaybe next) week. So feel free to merge it in advance.

**Comment by victor-torres** [comment]
If you guys don’t mind, I would wait for the tests to be implemented ;)

**Comment by TomKemperNL** [comment]
I've got them 'working on my pc' and on AppVeyor. Travis is complaining about something with their mercurial installation (I can't update using relative references like p1(tip) for the first parent of the tip). Learned a lot of useless things about Mercurial in the process.

Did you know that when you update (at least on windows) with

>hg up 'bookmarkname' 

It will update to the bookmark, but not activate it.

>hg up "bookmarkname"

 works just fine?


Lovely

**Comment by TomKemperNL** [comment]
You were right Victor. I couldn't reproduce the Travis error on my local machine, but now I've got a travis docker-image running and indeed: There be bugs.

Apparently parsing the secret ./.hg/bookmarks.current file doesn't work in hg version 2.0.2.

**Comment by victor-torres** [comment]
Reviewing the code here and seems like it’s fine to merge. 

Can we merge, @TomKemperNL?

**Comment by TomKemperNL** [comment]
I'd say merge it. I'll finish the tests 'someday' and we'll fix the hg version 2 issues then.

I'll create a new issue for this after you've merged it.

(I mean, it doesn't do anything nasty on hg 2, it just doesn't work yet)

**Comment by danielmachado** [comment]
Sorry guys, i couldn't find any time in a while to take a look into this.

My knowledge about Coffee-Script is extreamly limited (this is my first code in this language) so adding specs probably take me too much time in this case and i haven't so much nowadays.

**Pull request merged**
